DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'morubi_app') THEN
    CREATE ROLE morubi_app LOGIN PASSWORD 'morubi_app' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'morubi_auth') THEN
    CREATE ROLE morubi_auth LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
END
$$;

GRANT CONNECT ON DATABASE morubi TO morubi_app;
GRANT USAGE ON SCHEMA public TO morubi_app;
GRANT CONNECT ON DATABASE morubi TO morubi_auth;
GRANT USAGE ON SCHEMA public TO morubi_auth;
